# Welcome to Jekyll!
#

# Site settings
title: tekhin '16
description: |
  Phnom Penh's Technology Integration Conference for Teachers
  Oct 22nd at ISPP
owner:  Tekhx Phnom Penh
first_published: 2016 
email: lyle@asianhope.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.tekhx.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/tekhx
  facebook-official: https://facebook.com/tekhx
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
